services: 
  backend:
    build:
      context: ./backend
    container_name: mern-todo-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mern-todo-mongo-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
